version: "3.8"

services:
  frontend:
    build:
      context: ./Frontend
    container_name: frontendcon
    depends_on:
      - backend
    ports:
      - '5173:5173'
    networks:
      - medianetwork

  backend:
    build:
      context: ./Backend
    container_name: backendcon
    depends_on:
      - database
    ports:
      - '4000:4000'
    env_file:
      - './Backend/.env'
    networks:
      - medianetwork

  database:
    image: mongo
    container_name: mongocon
    ports:
      - '27017:27017'
    networks:
      - medianetwork

networks:
  medianetwork:
